Revert "Merge branch 'master' into customisation"
This reverts commit 4d075c4b33cfef0548339c7f43e62d12f72a19e9, reversing
changes made to 268f120961bca1eb5e35826644496965cd2162ba.

diff --git a/tgui/bin/tgui b/tgui/bin/tgui
--- a/tgui/bin/tgui
+++ b/tgui/bin/tgui
@@ -67,7 +67,7 @@ task-lint() {
   cd "${base_dir}"
   yarn run tsc
   echo "tgui: type check passed"
-  yarn run eslint packages --ext .js,.cjs,.ts,.tsx "${@}"
+  yarn run eslint packages --ext .js,.jsx,.ts,.tsx,.cjs,.mjs "${@}"
   echo "tgui: eslint check passed"
 }
 
@@ -82,20 +82,30 @@ task-clean() {
   ## Build artifacts
   rm -rf public/.tmp
   rm -f public/*.map
-  rm -f public/*.chunk.*
-  rm -f public/*.bundle.*
   rm -f public/*.hot-update.*
   ## Yarn artifacts
   rm -rf .yarn/cache
   rm -rf .yarn/unplugged
   rm -rf .yarn/webpack
-  rm -f .yarn/build-state.yml
-  rm -f .yarn/install-state.gz
-  rm -f .yarn/install-target
+  rm -rf .yarn/build-state.yml
+  rm -rf .yarn/install-state.gz
   rm -f .pnp.js
   ## NPM artifacts
   rm -rf **/node_modules
   rm -f **/package-lock.json
+}
+
+## Validates current build against the build stored in git
+task-validate-build() {
+  cd "${base_dir}"
+  local diff
+  diff="$(git diff packages/tgui/public/tgui.bundle.*)"
+  if [[ -n ${diff} ]]; then
+    echo "Error: our build differs from the build committed into git."
+    echo "Please rebuild tgui."
+    exit 1
+  fi
+  echo "tgui: build is ok"
 }
 
 ## Installs merge drivers and git hooks
@@ -139,6 +149,18 @@ if [[ ${1} == "--install-git-hooks" ]]; then
   task-install-git-hooks
   exit 0
 fi
+
+## Continuous integration scenario
+if [[ ${1} == "--ci" ]]; then
+  task-clean
+  task-install
+  task-lint
+  task-test
+  task-webpack --mode=production
+  task-validate-build
+  exit 0
+fi
+
 
 if [[ ${1} == "--clean" ]]; then
   task-clean
